# Generated by Django 3.0.5 on 2020-04-21 17:06

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200420_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=cloudinary.models.CloudinaryField(default='1', max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
